spring:
  data:
    mongodb:
      uri: mongo-uri
      database: journaldb
      auto-index-creation: true


  profiles:
    active: dev

weather:
  api:
    key: enter-your-key
  complete:
    api: enter-your-api