spring:
  data:
    mongodb:
      uri: mongodb-uri
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: gmail@gmail.com
    password: xxxx xxxx xxxx xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  profiles:
    active: dev

weather:
  api:
    key: key