spring:
  redis:
#    host: localhost
#    port: 6379
    host: host
    port: port
    password: password
  data:
    mongodb:
      uri: db-uri
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: gmail@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  profiles:
    active: dev

weather:
  api:
    key: key