spring:
  data:
    mongodb:
      uri: mongodb+srv://ssid7074:3TyzIAHYM51KO5fM@cluster0.vl44har.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssid7074@gmail.com
    password: frqw prms bdxu jpzq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  profiles:
    active: dev

weather:
  api:
    key: caf8e2a357024793efedaffa31fec31f